### ISSUE TITLE
preprocess module not found

### ISSUE THREAD

**Issue by Destiny-Designer1197** [claws-lab/TDAP#1]
Can someone please help me in solving this
1.'preprocess not found in dataset.py
2.  and also in utils.py 'graph' and 'tol' not defined

**Comment by Jieerbobo** [comment]
Hi, have you solved these issues and run the model?

**Comment by Ksartik** [comment]
Hi, I am really sorry I didn't see these issues earlier. I have added the preprocess file now. As for graph and tol in utils.py, I have also removed those functions because we never use them.
